<html>  <head>   <link rel="shortcut icon" href="http://i.imgur.com/6nDDWzt.png" />   <meta property="og:title" content="Extreme Crew"/>   <meta property="og:description" content="Hacked By Achon666ju5t"/>   <title>Extreme Crew</title>   <link href='http://fonts.googleapis.com/css?family=Megrim' rel='stylesheet' type='text/css'>   <link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>     <script src="http://e-mete.com/js/kdsnow.js"></script>  <style>    body{     background-image: url(index.html);     background-repeat: no-repeat;      background-attachment: fixed;      background-position: top;     background-color:#000000;     position: relative;     background-size:100% 100vh;          }    .logo {     width: 300px;     height: 300px;     margin: 0 auto;     margin-top: 50px;     -webkit-filter: drop-shadow(0px 0px 7px #0080FF);     filter: drop-shadow(0px 0px 7px #0080FF);    }    .logo:hover{     width: 300px;     height: 300px;     -webkit-filter: drop-shadow(0px 0px 10px #0080FF);     opacity:0.4;     filter:alpha(opacity=40);     transition: opacity .2s ease-out;     -moz-transition: opacity .2s ease-out;     -webkit-transition: opacity .2s ease-out;     -o-transition: opacity .2s ease-out;    }    .defacedby{     font-family: Megrim;     text-align: center;     color: black;     font-weight: bold;     font-size: 50px;   text-shadow: #0080FF 1px 2px 1px;        }    .glow {     font-family: Quicksand;     text-align: center;     color: grey;     font-style: bold;     font-size: 15px;    margin-top: 16px;    text-shadow: black 1px 2px 1px;        }    .greetings{     font-family: Quicksand;     text-align: center;     color: #ffffff;     font-size: 15px;     margin-top: 50px; text-shadow: black 1px 2px 1px;    }    </style>   </head>    <body>   <script>    alert('zuahahaahahha Achon666ju5t Was Here!')   </script>   <center>
    <img src="http://zonehmirrors.org/defaced/2016/12/07/abklimhamn.se/i.imgur.com/6nDDWzt.png" class="logo"></img><br>   </center>
</div>
<div class="glow">
    <h2>
<b><font color=red>"Hacked b<font color=white>y Achon666ju5t" <b></h2>
<font color=cyan> Pengadilan Negri ya? Mau Lapor dong cewe ane kena tikung :') Tolong Di adili sadja min :') Penikung ban*sat ya min? Kaya galaku aja nikung cewe orang lain :')<br><br>We are : <br>sn0wden - Kinal Undetected - Mr.AchanX48  - Ndivic404 - McQueen_404 - D4RKNE55 - Chinax1337<br> Achon666ju5t - Mr.LittleHaxor  - ./51N1CH1 - fcod3x - KidSZonk - Mr.DreamX196 - ./R015 - FORBID3N <br> </div>
<div class="greetings">
   <b><font color=white>Greetz To :<br>AZZATSZIN - T1KUS90T - ./MaulaniKartika07<br><br>Contact: frendy666.rf@gmail.com   </footer>     </div>
<embed src="https://www.youtube.com/v/v=loCEj0Rj5NY&autoplay=1" type="application/x-shockwave-flash" wmode="transparent" width="1" height="1"></embed>  </body> </html>
